default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: db/production.sqlite3

development:
  username: root
  password: password
  adapter: mysql2
  database: mp_development
  encoding: utf8
  pool: 5
  timeout: 5000

test:
  username: root
  password: password
  adapter: mysql2
  database: mp_test
  encoding: utf8
  pool: 5
  timeout: 5000
